markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: wuukee
author: "吴珂"
email: 254370923@qq.com
name: "吴珂个人博客"
url: http://wuukee.github.io
domain: wuukee.github.io
all_categories: [
["java", "Java","/posts/java.html"], 
["python", "Python","/posts/python.html"], 
["linux", "Linux","/posts/linux.html"],
["mysql", "MySQL","/posts/mysql.html"],
["run", "长跑","/posts/run.html"], 
["other", "其他","/posts/other.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate

leancloud:
  enable: true
  app_id: wVw6nXrsJozp7Gm8tTsQ6PDU-gzGzoHsz
  app_key: E3mBl3AUoLsYGj7QAvRFecmu
  
comments:
  gitalk: true
  gitalk_clientID: '93f96a914a7d36346e97'
  gitalk_Secret: '9e5bac1b92247f2411fb8e3bf48944d1766a0441'
  gitalk_repo: 'wuukee.github.io'
  gitalk_owner: 'wuukee'
  gitalk_admin: 'wuukee'
  distractionFreeMode: true 
